### ISSUE TITLE
New accounts name is confusing

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/lerna#164]
<img width="270" alt="screen shot 2016-05-17 at 8 17 27 pm" src="https://cloud.githubusercontent.com/assets/92044/15344425/6b0046c4-1c6c-11e6-8418-f26efdcbe927.png">

If I didn't know any better, I'd think that Account name was for my personal name rather than my site name. Can we do something to clarify?

**Comment by cbeer** [comment]
We still need to design the whole process.

**Comment by jcoyne** [comment]
Fixed by #274
