### ISSUE TITLE
FileSetPresenter should have a way to get the id of the original file.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/lerna#174]
So we can use IIIF:

Currently I have to do this:
```ruby
link_to 'IIIF', riiif.image_path(FileSet.find(file_set_presenter.id).files.first.id, size: '640,')
```
We could index the `original_file_id` in the `FileSetIndexer`.

**Comment by tpendragon** [comment]
> We could index the original_file_id in the FileSetIndexer.

:+1: Should probably happen in CC.

**Comment by jcoyne** [comment]
No longer necessary as we've moved this into the https://github.com/projecthydra-labs/lerna/blob/master/app/services/iiif_thumbnail_path_service.rb
