### ISSUE TITLE
UI customization: landing page background image

### ISSUE THREAD

**Issue by hannahfrost** [projecthydra-labs/lerna#285]
As a repository admin, I need to change the nav bar background image via the settings UI, so that I can easily customize the look of my repository.

Just a upload form and list the required dimensions for the upload. (no crop tool for right now)

**Comment by jcoyne** [comment]
Do we need to have a crop tool after uploading, or can we specify an image size for them to create?

**Comment by hannahfrost** [comment]
@jcoyne Crop tool would be great. And don't we also need to specify minimum image size for best results, regardless of crop tool?

**Comment by jcoyne** [comment]
If we specify an exact image size, we wouldn't need a crop tool, we can choose to put the responsibility on the person doing the configuration.

**Comment by hannahfrost** [comment]
I think users are accustomed to a crop tool for things like profile images; it seems a bit odd for a banner image that spans the full window.

**Comment by jcoyne** [comment]
We need to chat about the acceptance criteria of this story on our call today.

**Comment by hannahfrost** [comment]
OK, this ticket is done when a repository admin: 
- [ ] can upload a background image (in TIFF, JPG, or PNG formats?) using a file uploader or drag-n-drop
- [ ] gets an indication that the upload was completed successfully or a failure
- [ ] can crop the image to fit the background area 
- [ ] can save the results of these activities

**Comment by jcoyne** [comment]
Still needs more detail about what

> can crop the image to fit the background area

should be.

**Comment by hannahfrost** [comment]
Do you mean the cropping interaction or size of resulting crop? Now that I have used the cropping tool in Spotlight, I was envisioning something like that.

**Comment by jcoyne** [comment]
We can do that, but it probably should be a separate ticket, as it is so much work.

**Comment by mjgiarlo** [comment]
Design needed. Tagging @ggeisler

**Comment by mjgiarlo** [comment]
While some design is needed for this issue, ultimately, we can start by porting over the work that this team did on Spotlight earlier this summer.

**Comment by jcoyne** [comment]
I think it's still too early to begin work.  Are we just talking about the background image on the landing page?  https://sonics.demo.hydrainabox.org/ ? Are we talking about porting the IIIF crop tool or the jquery-crop tool?

**Comment by mjgiarlo** [comment]
Yes, we're talking about the background image on the landing page. (Updated the issue to clarify. Thanks!)

I'm ambivalent on whether or not we use the IIIF crop tool or jquery-crop. What are the trade-offs of that choice?

**Comment by mjgiarlo** [comment]
To clarify this ticket, the initial requirement will be that images must be uploaded with a given size (the same size as Sufia's "tulips" image) and file format (jpg/gif/png).

**Comment by tdonohue** [comment]
Note: beginning work over at https://github.com/projecthydra-labs/lerna/tree/285_landing_image
Extremely early work, nowhere near fully functional. But, early comments are welcome, especially since it's been a while since I've done Rails development.
