### ISSUE TITLE
Abandon rubocop-rspec?

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/lerna#296]
This seems a bit crazy: https://travis-ci.org/projecthydra-labs/lerna/builds/156098757  I'm a bit sick of fixing all these new issues ever few weeks.  Are we deriving benefit from this?

**Comment by atz** [comment]
Yeah, I've been having to set a lot more exceptions since rubocop-rspec started deciding it knows more than it actually does about our context.   I'm happy disabling large parts of it or getting rid of it.  It's a pain to include as it is anyway.

**Comment by atz** [comment]
That being said, our tests are frequently the ugliest part of the codebase, so I understand the instinct that *something* should be done.
